export const wordSequence = [
  {
    text: "PANIC",
    duration: 700,
    effect: "zoom-in",
    color: "text-red-500",
    size: "text-7xl",
  },
  {
    text: "SYSTEM FAILURE",
    duration: 500,
    effect: "slide-up",
    color: "text-yellow-500",
    size: "text-6xl",
  },
  {
    text: "BROKEN",
    duration: 400,
    effect: "flicker",
    color: "text-red-600",
    size: "text-8xl",
  },
  {
    text: "CRISIS",
    duration: 350,
    effect: "zoom-in",
    color: "text-orange-500",
    size: "text-7xl",
  },
  {
    text: "CHAOS",
    duration: 300,
    effect: "shake",
    color: "text-red-400",
    size: "text-7xl",
  },
  {
    text: "ERROR",
    duration: 300,
    effect: "glitch",
    color: "text-red-500",
    size: "text-7xl",
  },
  {
    text: "ALERT",
    duration: 250,
    effect: "pulse",
    color: "text-yellow-500",
    size: "text-6xl",
  },
  {
    text: "EMERGENCY",
    duration: 350,
    effect: "slide-left",
    color: "text-red-600",
    size: "text-6xl",
  },
  {
    text: "UNSTABLE",
    duration: 300,
    effect: "rotate",
    color: "text-yellow-400",
    size: "text-6xl",
  },
  {
    text: "CORRUPTED",
    duration: 300,
    effect: "glitch",
    color: "text-red-500",
    size: "text-6xl",
  },
  {
    text: "FIX IT",
    duration: 400,
    effect: "pulse",
    color: "text-blue-500",
    size: "text-7xl",
  },
  {
    text: "RECOVER",
    duration: 400,
    effect: "slide-up",
    color: "text-blue-600",
    size: "text-7xl",
  },
  {
    text: "REBUILD",
    duration: 450,
    effect: "zoom-in",
    color: "text-blue-500",
    size: "text-7xl",
  },
  {
    text: "RECOMPILE",
    duration: 500,
    effect: "slide-left",
    color: "text-green-500",
    size: "text-6xl",
  },
  {
    text: "STABILIZE",
    duration: 550,
    effect: "zoom-in",
    color: "text-green-600",
    size: "text-7xl",
  },
  {
    text: "DEPLOY",
    duration: 800,
    effect: "pulse",
    color: "text-green-500",
    size: "text-8xl",
  },
];
