version: "3.8"

services:
  app:
    container_name: portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
