export type CodeType = "reactComponent" | "cssStyles" | "animation";

export const codeContent: Record<CodeType, string[]> = {
  reactComponent: [
    "import React from 'react';",
    "import { motion } from 'framer-motion';",
    "import './Portfolio.css';",
    "",
    "const Portfolio = () => {",
    "  return (",
    '    <div className="portfolio-container">',
    "      <header>",
    "        <h1>My Portfolio</h1>",
    "      </header>",
    "      <main>",
    '        <section className="projects">',
    "          {/* Projects will be loaded dynamically */}",
    "        </section>",
    "      </main>",
    "    </div>",
    "  );",
    "};",
    "",
    "export default Portfolio;",
  ],
  cssStyles: [
    "/* Portfolio.css */",
    ".portfolio-container {",
    "  width: 100%;",
    "  max-width: 1200px;",
    "  margin: 0 auto;",
    "}",
    "",
    "header {",
    "  padding: 2rem 0;",
    "}",
    "",
    ".projects {",
    "  display: grid;",
    "  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));",
    "  gap: 2rem;",
    "}",
  ],
  animation: [
    "// Animation.js",
    "export const pageTransition = {",
    "  hidden: { opacity: 0, y: 30 },",
    "  visible: { ",
    "    opacity: 1, ",
    "    y: 0,",
    "    transition: {",
    "      type: 'spring',",
    "      stiffness: 260",
    "    }",
    "  }",
    "};",
  ],
};
