export const codeSnippets = [
  "import React, { useState, useEffect, useRef, lazy, Suspense } from 'react';",
  "import { ThemeProvider } from './components/base/ThemeProvider';",
  "import PersonalHeader from './components/home/intro/PersonalHeader';",
  "import NavigationBar from './components/home/appbar/NavigationBar';",
  "import InfiniteVoid from './components/base/InfiniteVoid';",
  "",
  "// Lazy loaded components for performance optimization",
  "const Skills = lazy(() => import('./components/home/skills/Skills'));",
  "const Projects = lazy(() => import('./components/home/projects/Projects'));",
  "const WorkExperience = lazy(() => import('./components/home/work/WorkExperience'));",
  "const Articles = lazy(() => import('./components/home/articles/Articles'));",
  "const ContactMe = lazy(() => import('./components/home/contact/ContactMe'));",
  "",
  "function App() {",
  "  const [activeSection, setActiveSection] = useState('home');",
  "  const [isGridAnimationComplete, setIsGridAnimationComplete] = useState(false);",
  "  const appRef = useRef(null);",
  "",
  "  useEffect(() => {",
  "    // Initialize application components and load resources",
  "    document.documentElement.classList.add('dark');",
  "    return () => {",
  "      // Cleanup resources on unmount",
  "      document.documentElement.classList.remove('dark');",
  "    };",
  "  }, []);",
  "",
  "  // Map of available sections in the application",
  "  const sections = {",
  "    home: <PersonalHeader />,",
  "    skills: <Skills />,",
  "    projects: <Projects />,",
  "    experience: <WorkExperience />,",
  "    articles: <Articles />,",
  "    contact: <ContactMe />,",
  "  };",
  "",
  "  return (",
  "    <ThemeProvider defaultTheme='dark'>",
  "      {!isGridAnimationComplete ? (",
  "        <InfiniteVoid onAnimationComplete={() => setIsGridAnimationComplete(true)} />",
  "      ) : (",
  "        <>",
  "          <NavigationBar",
  "            onNavClick={(section) => setActiveSection(section)}",
  "            activeSection={activeSection}",
  "          />",
  "          <div className='min-h-screen bg-[#030712] w-full overflow-y-auto p-8 flex flex-col'>",
  "            <main className='flex flex-col flex-1'>",
  "              <Suspense fallback={<div className='h-96 animate-pulse bg-[#1e293b33] rounded-lg' />}>",
  "                <div className='animate-fadeIn h-full'>",
  "                  {sections[activeSection]}",
  "                </div>",
  "              </Suspense>",
  "            </main>",
  "          </div>",
  "        </>",
  "      )}",
  "    </ThemeProvider>",
  "  );",
  "}",
  "",
  "export default App;",
];

// Different stages of compilation
export const COMPILE_STAGES = [
  "Initializing build environment...",
  "Installing dependencies...",
  "Optimizing assets...",
  "Analyzing bundle size...",
  "Transpiling TypeScript...",
  "Compressing resources...",
  "Generating production build...",
];
