# Base image
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Start development server with host flag to allow external access
CMD ["npm", "run", "dev", "--", "--host"]