export const messages = [
  "Wait, someone is visiting my portfolio...",
  "Oh no! The site isn't ready yet!",
  "They're looking at my unfinished code!",
  "I need to build this ASAP!",
  "Quick, let's go build it 😨!",
];

export const codeLines = [
  "/* Portfolio component needs to be completed before the deadline! */",
  "import React from 'react';",
  "import { Card, CardContent } from '@/components/ui/card';",
  "import { Button } from '@/components/ui/button';",
  "",
  "const Portfolio = () => {",
  "  const [activeSection, setActiveSection] = useState('home');",
  "",
  "  const sections = {",
  "    home: <HomeSection />,",
  "    skills: <SkillsSection />,",
  "    projects: <ProjectsSection />,",
  "    experience: <ExperienceSection />,",
  "    contact: <ContactSection />",
  "  };",
  "",
  "   /* Remember to add animations to section transitions */",
  "  return (",
  "    <div className='min-h-screen bg-gradient-to-b from-slate-950 to-slate-900'>",
  "      <header className='py-4 px-6 flex justify-between items-center'>",
  "        /* Fix the mobile responsiveness issues */",
  "        <div className='text-xl font-bold'>Utkarsh.me</div>",
  "        <nav className='flex gap-4'>",
  "          {/* TODO: Add navigation links */}",
  "        </nav>",
  "      </header>",
  "",
  "      <main>",
  "        {/* TODO: Finish implementing sections */}",
  "        {sections[activeSection]}",
  "      </main>",
  "    </div>",
  "  );",
  "};",
  "",
  "export default Portfolio;",
];

export const codeCommentsLines = [
  "/* Portfolio component needs to be completed before the deadline! */",
  "/* Remember to add animations to section transitions */",
  "/* Fix the mobile responsiveness issues */",
  "/* Need to optimize image loading and performance */",
  "/* Add proper accessibility attributes */",
];
