const CHAT_TIMING = 5000;
const CODING_TIMING = 6000;
const COMMANDS_TIMING = 1500;
const BROWSER_TIMING = 10000;
const TERMINAL_TIMING = 10000;
const INITIAL_DELAY = 600;

export {
  CHAT_TIMING,
  CODING_TIMING,
  COMMANDS_TIMING,
  BROWSER_TIMING,
  INITIAL_DELAY,
  TERMINAL_TIMING,
};
